version: "3.6"

networks:
  alpine-net:
    driver: bridge

volumes:
    v-alpine-mysql:
    v-alpine-es:

services:
  # ----------------------------------------------
  # MySQL
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0.21
    env_file:
      - .env
      - .sec_env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: alpine
    volumes:
      # - mysql-data:/var/lib/mysql
      - v-alpine-mysql:/var/lib/mysql
    networks:
      - alpine-net

  # ----------------------------------------------
  # Elasticsearch Stack
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - cluster.name=es-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-XX:UseAVX=2 -Xms512M -Xmx512M"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      # - elasticsearch-data:/usr/share/elasticsearch/data
      - v-alpine-es:/usr/share/elasticsearch/data
    networks:
      - alpine-net
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  # Kibana
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.8.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - alpine-net
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5602/api/status

# ----------------------------------------------
# Alpine App
  alpine:
    container_name: alpine
    image: alpine:latest
    ports:
      - 8000:5000
    env_file:
      - .env
      - .sec_env
    depends_on:
      - mysql
      - elasticsearch
    environment:
      MAIL_SERVER: smtp.googlemail.com
      MAIL_PORT: 587
      MAIL_USE_TLS: "true"
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - alpine-net
    restart: always
