"""add claim and is_creator and is_on_market

Revision ID: 00fbdde2bc0d
Revises: 55954d2561cb
Create Date: 2021-05-08 16:54:45.553921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fbdde2bc0d'
down_revision = '55954d2561cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_claim_tag_id_tag')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_claim_user_id_user')),
    sa.PrimaryKeyConstraint('id', 'user_id', 'tag_id', name=op.f('pk_claim'))
    )
    # op.drop_table('deck')
    # with op.batch_alter_table('card', schema=None) as batch_op:
    #     batch_op.drop_constraint('fk_card_deck_id_deck', type_='foreignkey')
    #     batch_op.drop_column('deck_id')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_on_market', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_creator', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_creator')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('is_on_market')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_card_deck_id_deck', 'deck', ['deck_id'], ['id'])

    # op.create_table('deck',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('name', sa.VARCHAR(length=256), nullable=True),
    # sa.Column('timestamp', sa.DATETIME(), nullable=True),
    # sa.Column('user_id', sa.INTEGER(), nullable=True),
    # sa.Column('description', sa.VARCHAR(length=1024), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_deck_user_id_user'),
    # sa.PrimaryKeyConstraint('id', name='pk_deck')
    # )
    op.drop_table('claim')
    # ### end Alembic commands ###
