"""remove source and example

Revision ID: 13a851c586df
Revises: 73db263fe702
Create Date: 2020-09-27 13:32:50.601287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a851c586df'
down_revision = '73db263fe702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('example')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example', sa.VARCHAR(length=2048), nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=2048), nullable=True))

    # ### end Alembic commands ###
