"""DEV-54 Decouple SpacedRep from Card

Revision ID: 16795b2ee0df
Revises: c08bce10bc7b
Create Date: 2021-03-04 23:20:03.885792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "16795b2ee0df"
down_revision = "c08bce10bc7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learn_spaced_repetition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("next_date", sa.DateTime(), nullable=True),
        sa.Column("bucket", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learn_spaced_repetition")),
    )
    with op.batch_alter_table("learn_spaced_repetition", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_learn_spaced_repetition_next_date"),
            ["next_date"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_learn_spaced_repetition_timestamp"),
            ["timestamp"],
            unique=False,
        )

    with op.batch_alter_table("card", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("learn_spaced_rep_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_card_learn_spaced_rep_id_learn_spaced_repetition"),
            "learn_spaced_repetition",
            ["learn_spaced_rep_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("card", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_card_learn_spaced_rep_id_learn_spaced_repetition"),
            type_="foreignkey",
        )
        batch_op.drop_column("learn_spaced_rep_id")

    with op.batch_alter_table("learn_spaced_repetition", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_learn_spaced_repetition_timestamp"))
        batch_op.drop_index(batch_op.f("ix_learn_spaced_repetition_next_date"))

    op.drop_table("learn_spaced_repetition")
    # ### end Alembic commands ###
