"""add tag description real

Revision ID: 55954d2561cb
Revises: dc2171dec341
Create Date: 2021-03-21 14:10:47.309436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55954d2561cb"
down_revision = "dc2171dec341"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('deck')
    # with op.batch_alter_table('card', schema=None) as batch_op:
    #     batch_op.drop_constraint('fk_card_deck_id_deck', type_='foreignkey')
    #     batch_op.drop_column('deck_id')

    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.String(length=1028), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_column("description")

    with op.batch_alter_table("card", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deck_id", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key("fk_card_deck_id_deck", "deck", ["deck_id"], ["id"])

    # op.create_table(
    #     "deck",
    #     sa.Column("id", sa.INTEGER(), nullable=False),
    #     sa.Column("name", sa.VARCHAR(length=256), nullable=True),
    #     sa.Column("timestamp", sa.DATETIME(), nullable=True),
    #     sa.Column("user_id", sa.INTEGER(), nullable=True),
    #     sa.Column("description", sa.VARCHAR(length=1024), nullable=True),
    #     sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_deck_user_id_user"),
    #     sa.PrimaryKeyConstraint("id", name="pk_deck"),
    # )
    # ### end Alembic commands ###
