"""increase max char Card back

Revision ID: 59357e214461
Revises: 5b8fb987c2d8
Create Date: 2020-08-04 23:23:56.634633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59357e214461'
down_revision = '5b8fb987c2d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'back',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'back',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
    # ### end Alembic commands ###
