"""empty message

Revision ID: 9c41c7015ef3
Revises: c08bce10bc7b
Create Date: 2021-02-28 08:39:17.823247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c41c7015ef3'
down_revision = 'c08bce10bc7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_tag_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag'))
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_timestamp'), ['timestamp'], unique=False)

    op.create_table('tagging',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_tagging_card_id_card')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_tagging_tag_id_tag')),
    sa.PrimaryKeyConstraint('tag_id', 'card_id', name=op.f('pk_tagging'))
    )
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_index('ix_deck_timestamp')

    op.drop_table('deck')
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_constraint('fk_card_deck_id_deck', type_='foreignkey')
        batch_op.drop_column('deck_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_card_deck_id_deck', 'deck', ['deck_id'], ['id'])

    op.create_table('deck',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_deck_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_deck')
    )
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.create_index('ix_deck_timestamp', ['timestamp'], unique=False)

    op.drop_table('tagging')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_timestamp'))

    op.drop_table('tag')
    # ### end Alembic commands ###
