"""add LearningSessionFact

Revision ID: c08bce10bc7b
Revises: b815dc9607a2
Create Date: 2021-02-01 06:55:50.791441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c08bce10bc7b"
down_revision = "b815dc9607a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_session_fact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ls_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("start_at", sa.DateTime(), nullable=True),
        sa.Column("complete_at", sa.DateTime(), nullable=True),
        sa.Column("is_ok", sa.Boolean(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"], ["card.id"], name=op.f("fk_learning_session_fact_card_id_card")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_learning_session_fact_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_session_fact")),
    )
    with op.batch_alter_table("learning_session_fact", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_learning_session_fact_card_id"), ["card_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_learning_session_fact_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_learning_session_fact_ls_id"), ["ls_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_learning_session_fact_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("current_ls_id", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("current_ls_id")

    with op.batch_alter_table("learning_session_fact", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_learning_session_fact_user_id"))
        batch_op.drop_index(batch_op.f("ix_learning_session_fact_ls_id"))
        batch_op.drop_index(batch_op.f("ix_learning_session_fact_created_at"))
        batch_op.drop_index(batch_op.f("ix_learning_session_fact_card_id"))

    op.drop_table("learning_session_fact")
    # ### end Alembic commands ###
