"""DEV-114 Remove card back limit character

Revision ID: f2efdd407976
Revises: 13a6be76ac3b
Create Date: 2021-05-15 15:42:32.653477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f2efdd407976"
down_revision = "13a6be76ac3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('deck')
    with op.batch_alter_table("card", schema=None) as batch_op:
        batch_op.alter_column(
            "back",
            existing_type=sa.VARCHAR(length=1000),
            type_=sa.Text(),
            existing_nullable=True,
        )
        # batch_op.drop_constraint('fk_card_deck_id_deck', type_='foreignkey')
        # batch_op.drop_column('deck_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("card", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deck_id", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key("fk_card_deck_id_deck", "deck", ["deck_id"], ["id"])
        batch_op.alter_column(
            "back",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(length=1000),
            existing_nullable=True,
        )

    # op.create_table(
    #     "deck",
    #     sa.Column("id", sa.INTEGER(), nullable=False),
    #     sa.Column("name", sa.VARCHAR(length=256), nullable=True),
    #     sa.Column("timestamp", sa.DATETIME(), nullable=True),
    #     sa.Column("user_id", sa.INTEGER(), nullable=True),
    #     sa.Column("description", sa.VARCHAR(length=1024), nullable=True),
    #     sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_deck_user_id_user"),
    #     sa.PrimaryKeyConstraint("id", name="pk_deck"),
    # )
    # ### end Alembic commands ###
